services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: app-db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
